
verticalUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexL is IndexL-1,
NewIndexL > 0,
accesElement(Board,NewIndexL,IndexC,E),
var(E),!,
fail.
verticalUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexL is IndexL-1,
NewIndexL > 0,
accesElement(Board,NewIndexL,IndexC,E),
var(E),
giveValue((NewIndexL,IndexC),R),!.
verticalUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexL is IndexL-1,
NewIndexL > 0,
accesElement(Board,NewIndexL,IndexC,E),
E=:=Player,!,
fail.
verticalUp(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexL is IndexL-1,
NewIndexL > 0,
accesElement(Board,NewIndexL,IndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
verticalUp(Board,(NewIndexL,IndexC),Player,NewCounter,R).
verticalUp(Board,(1,IndexC),Player,Counter,R) :- Counter > 0,
accesElement(Board,1,IndexC,E),
E =:= 1-Player,
!,fail.

verticalDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexL is IndexL+1,
NewIndexL < 9,
accesElement(Board,NewIndexL,IndexC,E),
var(E),!,
fail.
verticalDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexL is IndexL+1,
NewIndexL < 9,
accesElement(Board,NewIndexL,IndexC,E),
var(E),
giveValue((NewIndexL,IndexC),R),!.
verticalDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexL is IndexL+1,
NewIndexL < 9,
accesElement(Board,NewIndexL,IndexC,E),
E=:=Player,!,
fail.
verticalDown(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexL is IndexL+1,
NewIndexL < 9,
accesElement(Board,NewIndexL,IndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
verticalDown(Board,(NewIndexL,IndexC),Player,NewCounter,R).
verticalDown(Board,(8,IndexC),Player,Counter,R) :- Counter > 0,
accesElement(Board,8,IndexC,E),
E =:= 1-Player,
!,fail.

horizontalLeft(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexC is IndexC-1,
NewIndexC > 0,
accesElement(Board,IndexL,NewIndexC,E),
var(E),!,
fail.
horizontalLeft(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexC is IndexC-1,
NewIndexC > 0,
accesElement(Board,IndexL,NewIndexC,E),
var(E),
giveValue((IndexL,NewIndexC),R),!.
horizontalLeft(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexC is IndexC-1,
NewIndexC > 0,
accesElement(Board,IndexL,NewIndexC,E),
E=:=Player,!,
fail.
horizontalLeft(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexC is IndexC-1,
NewIndexC > 0,
accesElement(Board,IndexL,NewIndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
horizontalLeft(Board,(IndexL,NewIndexC),Player,NewCounter,R).
horizontalLeft(Board,(IndexL,1),Player,Counter,R) :- Counter > 0,
accesElement(Board,IndexL,1,E),
E =:= 1-Player,
!,fail.

horizontalRight(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexC is IndexC+1,
NewIndexC < 9,
accesElement(Board,IndexL,NewIndexC,E),
var(E),!,
fail.
horizontalRight(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexC is IndexC+1,
NewIndexC < 9,
accesElement(Board,IndexL,NewIndexC,E),
var(E),
giveValue((IndexL,NewIndexC),R),!.
horizontalRight(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexC is IndexC+1,
NewIndexC < 9,
accesElement(Board,IndexL,NewIndexC,E),
E=:=Player,!,
fail.
horizontalRight(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexC is IndexC+1,
NewIndexC < 9,
accesElement(Board,IndexL,NewIndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
horizontalRight(Board,(IndexL,NewIndexC),Player,NewCounter,R).
horizontalRight(Board,(IndexL,8),Player,Counter,R) :- Counter > 0,
accesElement(Board,IndexL,8,E),
E =:= 1-Player,
!,fail.

slashUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexC is IndexC-1,
NewIndexL is IndexL-1,
NewIndexC > 0,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),!,
fail.
slashUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexC is IndexC-1,
NewIndexL is IndexL-1,
NewIndexC > 0,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),
giveValue((NewIndexL,NewIndexC),R),!.
slashUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexC is IndexC-1,
NewIndexL is IndexL-1,
NewIndexC > 0,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=Player,!,
fail.
slashUp(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexC is IndexC-1,
NewIndexL is IndexL-1,
NewIndexC > 0,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
slashUp(Board,(NewIndexL,NewIndexC),Player,NewCounter,R).
slashUp(Board,(IndexL,1),Player,Counter,R) :- Counter > 0,
accesElement(Board,IndexL,0,E),
E =:= 1-Player,
!,fail.
slashUp(Board,(1,IndexC),Player,Counter,R) :- Counter > 0,
accesElement(Board,0,IndexC,E),
E =:= 1-Player,
!,fail.

slashDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexC is IndexC+1,
NewIndexL is IndexL+1,
NewIndexC < 9,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),!,
fail.
slashDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexC is IndexC+1,
NewIndexL is IndexL+1,
NewIndexC < 9,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),
giveValue((NewIndexL,NewIndexC),R),!.
slashDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexC is IndexC+1,
NewIndexL is IndexL+1,
NewIndexC < 9,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=Player,!,
fail.
slashDown(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexC is IndexC+1,
NewIndexL is IndexL+1,
NewIndexC < 9,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
slashDown(Board,(NewIndexL,NewIndexC),Player,NewCounter,R).
slashDown(Board,(IndexL,8),Player,Counter,R) :- Counter > 0,
accesElement(Board,IndexL,8,E),
E =:= 1-Player,
!,fail.
slashDown(Board,(8,IndexC),Player,Counter,R) :- Counter > 0,
accesElement(Board,8,IndexC,E),
E =:= 1-Player,
!,fail.

antiSlashUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexC is IndexC+1,
NewIndexL is IndexL-1,
NewIndexC < 9,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),!,
fail.
antiSlashUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexC is IndexC+1,
NewIndexL is IndexL-1,
NewIndexC < 9,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),
giveValue((NewIndexL,NewIndexC),R),!.
antiSlashUp(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexC is IndexC+1,
NewIndexL is IndexL-1,
NewIndexC < 9,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=Player,!,
fail.
antiSlashUp(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexC is IndexC+1,
NewIndexL is IndexL-1,
NewIndexC < 9,
NewIndexL > 0,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
antiSlashUp(Board,(NewIndexL,NewIndexC),Player,NewCounter,R).
antiSlashUp(Board,(IndexL,8),Player,Counter,R) :- Counter > 0,
accesElement(Board,IndexL,8,E),
E =:= 1-Player,
!,fail.
antiSlashUp(Board,(1,IndexC),Player,Counter,R) :- Counter > 0,
accesElement(Board,0,IndexC,E),
E =:= 1-Player,
!,fail.

antiSlashDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter =:= 0,
NewIndexC is IndexC-1,
NewIndexL is IndexL+1,
NewIndexC > 0,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),!,
fail.
antiSlashDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter > 0,
NewIndexC is IndexC-1,
NewIndexL is IndexL+1,
NewIndexC > 0,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
var(E),
giveValue((NewIndexL,NewIndexC),R),!.
antiSlashDown(Board,(IndexL,IndexC),Player,Counter,R) :- Counter >= 0,
NewIndexC is IndexC-1,
NewIndexL is IndexL+1,
NewIndexC > 0,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=Player,!,
fail.
antiSlashDown(Board,(IndexL,IndexC),Player,Counter,R) :- NewIndexC is IndexC-1,
NewIndexL is IndexL+1,
NewIndexC > 0,
NewIndexL < 9,
accesElement(Board,NewIndexL,NewIndexC,E),
E=:=1-Player,
NewCounter is Counter+1,
antiSlashDown(Board,(NewIndexL,NewIndexC),Player,NewCounter,R).
antiSlashDown(Board,(8,IndexC),Player,Counter,R) :- Counter > 0,
accesElement(Board,8,IndexC,E),
E =:= 1-Player,
!,fail.
antiSlashDown(Board,(IndexL,1),Player,Counter,R) :- Counter > 0,
accesElement(Board,IndexL,0,E),
E =:= 1-Player,
!,fail.
